Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@renanaugust 
rafaballerini
/
rafaballerini
Public
Code
Issues
10
Pull requests
18
Actions
Projects
Security
Insights
Generate Datas
Generate Datas #2767
Jobs
Run details
Workflow file for this run
.github/workflows/cobrinha.yml at 3703d0e
name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: renanaugust
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
Update README.md · rafaballerini/renanaugust
